/**
 * Types for Senegalese ID Card system
 */

export interface IdCardForm {
  // --- étape 1 : identité
  nom: string;
  prenoms: string;
  date_naissance: string; // YYYY-MM-DD
  lieu_naissance: string;
  sexe: 'M' | 'F';
  taille_cm: number; // 50-250
  profession?: string;
  adresse: string;
  telephone: string;
  email?: string;

  // --- étape 2 : photo
  photo_file?: File; // uploaded → Supabase bucket
  photo_url?: string; // generated URL

  // --- étape 3 : signature canvas
  signature_base64?: string; // data-url PNG

  // --- consentement
  gdprConsent?: boolean;

  // --- auto-generated by back
  cedeaonumber: string; // SN-2025-######  (front displays without dashes)
  date_delivrance: string; // today
  date_expiration: string; // today + 10 years
  autorite: string; // SIP / DAKAR-PLATEAU (hard-coded for phase 1)
  serie_carte: string; // random alphanum 7 char 2275HLM5
}

export interface CNIPositions {
  // Front card positions (in pixels for 300dpi image)
  prenoms: { top: number; left: number; fontSize: string; fontWeight: string };
  nom: { top: number; left: number; fontSize: string; fontWeight: string };
  date_naissance: { top: number; left: number };
  lieu_naissance: { top: number; left: number };
  sexe: { top: number; left: number };
  taille: { top: number; left: number };
  cedeaonumber: { top: number; left: number; fontFamily: string };
  date_delivrance: { top: number; left: number };
  date_expiration: { top: number; left: number };
  autorite: { top: number; left: number; fontSize: string };
  serie_carte: { bottom: number; left: number; fontSize: string; opacity: string };
  photo: { top: number; right: number; width: string; height: string };
  signature: { bottom: number; right: number; height: string; width: string };
  barcode: { bottom: number; right: number; width: string; height: string };
}

export interface MRZData {
  line1: string;
  line2: string;
  documentType: string;
  countryCode: string;
  documentNumber: string;
  checkDigit1: string;
  birthDate: string;
  checkDigit2: string;
  sex: string;
  expiryDate: string;
  checkDigit3: string;
  optionalData: string;
  checkDigit4: string;
}

export interface CNICitizen {
  id: string;
  formData: IdCardForm;
  photoUrl?: string;
  irisLeftUrl?: string;
  irisRightUrl?: string;
  enrolledAt: string;
  enrolledToday?: boolean;
  mrzData?: MRZData;
}